### ISSUE TITLE
Update to latest implementation

### ISSUE THREAD

**Issue by akosma** [hfossli/SocketIO-Client-CPP-iOS-Builds#1]
The original project owner recently included Boolean type support in the component, would it be possible to update this repo to that version?

Thanks for this great work! It's really helpful.

**Comment by hfossli** [comment]
Sure! I'll publish the tag 1.6.0 right away.

**Comment by hfossli** [comment]
Sorry, this will take more time than expected.

**Comment by hfossli** [comment]
Can you please test that it is working as exepected by using 

```
pod 'SocketIO-Client-CPP', :git => 'https://github.com/hfossli/SocketIO-Client-CPP-iOS-Builds.git', :branch => 'master'
```

?

**Comment by hfossli** [comment]
It seems good to me, so I'm just pushing..

**Comment by akosma** [comment]
Thanks a lot! Everything working perfectly well.

**Comment by hfossli** [comment]
Thanks for the feedback.
