### ISSUE TITLE
error: #include <string> string file not found

### ISSUE THREAD

**Issue by coffeeGF** [hfossli/SocketIO-Client-CPP-iOS-Builds#2]
I download 'heade'r and '.a' files and copy into my Xcode project.
Then  ' #include <string>'  line in 'sio_client.h' file show "string file not found" error
Should i add some other libs to make it works fine?
thanks.

**Comment by hfossli** [comment]
Are you importing this to a *.m file or *.mm file? Can you expand the error? See where it originates from?

**Comment by coffeeGF** [comment]
When i added  #include "sio_client.h"   to  ViewController.m ,sio_client.h file show string file not found.
Then i changed the Viewcontroller.m to ViewController.mm ,the error disappeared.

**Comment by hfossli** [comment]
Perfect
