### ISSUE TITLE
Building iOS static libraries

### ISSUE THREAD

**Issue by andreasunterhuber** [hfossli/SocketIO-Client-CPP-iOS-Builds#5]
@hfossli do you have any hint how to build `SocketIO-Client-CPP` with actual commit/master for iOS (BigSur, Xcode 12+)? Any help would be very appreciated. I want to create static libraries and contribute them.

**Comment by hfossli** [comment]
No, sorry, I have no idea. I'm not using this anymore

**Comment by andreasunterhuber** [comment]
Thanks anyway! I was able to build it and write a public tutorial 👍

**Comment by andreasunterhuber** [comment]
@hfossli perhaps you want to mention it in your Readme.md: https://github.com/kim-company/socket.io-client-cpp-ios-static - it's a recent manual with actual versions.
